name = "MPIHaloArrays"
uuid = "e77e6532-e7cc-40ad-aebc-b383a150aff6"
authors = ["Miller, Samuel <smil@lle.rochester.edu>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
MPI = ">=0.19"
julia = ">= 1.6"